CREATE DATABASE RH_SERVICO;

USE RH_SERVICO;

CREATE TABLE COLABORADORES(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
IDADE INT,
SETOR VARCHAR(255),
SALARIO VARCHAR(255),
PRIMARY KEY(ID)
);

INSERT INTO COLABORADORES(NOME, IDADE, SETOR, SALARIO) VALUES ('Armando',25,'Almofarixado',1400);
INSERT INTO COLABORADORES(NOME, IDADE, SETOR, SALARIO) VALUES ('Leila',28,'Secretariado',2700);
INSERT INTO COLABORADORES(NOME, IDADE, SETOR, SALARIO) VALUES ('Marcia',35,'TI',5500);
INSERT INTO COLABORADORES(NOME, IDADE, SETOR, SALARIO) VALUES ('Lais',30,'Marketing',5700);
INSERT INTO COLABORADORES(NOME, IDADE, SETOR, SALARIO) VALUES ('Marcos',47,'Gerente',14000);

SELECT * FROM COLABORADORES WHERE SALARIO>2000;
SELECT * FROM COLABORADORES WHERE SALARIO<2000;

UPDATE COLABORADORES SET SALARIO = 1700 WHERE ID = 1;
